### ISSUE TITLE
Move Mods to a separate repository

### ISSUE THREAD

**Issue by politas** [rkagerer/KSP-Fwiffo-Repository#1]
Currently, adding this repo to CKAN with 

```
Fwiffos Dev Repo | https://github.com/rkagerer/KSP-Fwiffo-Repository/archive/master.tar.gz
```

is working, but that archive is pulling down the mod zip files in /mods as well, so it takes even longer to download as the main repo. Moving the mod storage into a separate repository would make things far more efficient, and then the mod folders could be moved to the root of the repo, like in KSP-CKAN/CKAN-meta

If you can do that, I'd be happy to add this repo to the repos list in the CKAN client with only one small request. I'd like your undertaking that only freely-distributable mods (CC, GPL, MIT, BSD, etc) will be added to the Mod storage and referenced from the repository. 

Speaking of which, you've got HyperEdit marked as "restricted", but the original is GPL-3.0.

**Comment by rkagerer** [comment]
Hi Myk,

Thanks for your interest in my humble little collection!  The link intended to be used is:

Fwiffo’s Dev Repo | https://github.com/rkagerer/KSP-Fwiffo-Repository/raw/master/CKAN-meta-fwiffo.zip

I think that grabs what you want, without the mod assets themselves.  I’d rather keep the whole project down to one repo, if possible.  I’m new to GitHub – am I doing this wrong?

The “restricted” attribute in my HyperEdit ckan was inherited from: https://github.com/KSP-CKAN/CKAN-meta/blob/master/HyperEdit/HyperEdit-1.4.ckan.  Looks like I started with an older version of the metadata, thanks for pointing out the discrepancy I’ve corrected it.

Did you notice any non-free-distributable work included?  Honestly, this just started out as a local repository for my own personal use and that remains my primary purpose.  Politas (I think that’s you?) suggested I move it to GitHub rather than Dropbox, and I figured it might be useful to others (at least until the official 1.1 is released soon).  As stated in the Readme.md, I make no guarantees on maintenance for it over the long term.  If there’s specific material in the file that concerns you, let me know.  Maybe I can contact the authors to get explicit permission instead of removing it.

Cheers,

-Richard

**Comment by politas** [comment]
Yep, Politas is me. I think I tried Fwiffo’s Dev Repo | https://github.com/rkagerer/KSP-Fwiffo-Repository/raw/master/CKAN-meta-fwiffo.zip before unsuccessfully, but maybe I was missing the "raw/" part. I'll try that. Could you add that to the Readme file?

That link does indeed work.

**Comment by politas** [comment]
No, all the mods you have now are freely-redistributable. But since some of your .ckan files are pointing to this repository, I just wanted to be sure you were on board as far keeping everything in a legal framework copyright-wise. I know there is a lot of debate on the validity of copyright, but CKAN's position is that we follow licenses. If you don't want to be tied to that, I've got no issues with you doing whatever you want, but in that case I'm not going to add an endorsement in the CKAN distribution. Explicit permission from authors would also be fine.

As far as the unguaranteed maintenance, that's pretty much in standing with the other alternate repositories we list.

**Comment by politas** [comment]
Do you have some automated build task that updates that zip file? An advantage of keeping the repo tied to a specific purpose is that the archive zip gets created on request, so it's always up to date.

**Comment by rkagerer** [comment]
Yes a one-button publish.bat in the repo, which builds the zip and uploads it all to GitHub.

> > If you don't want to be tied to that, I've got no issues with you doing whatever you want, but in that case I'm not going to add an endorsement in the CKAN distribution. Explicit permission from authors would also be fine.<<

Sounds good.  If the situation changes we can remove the endorsement.

Cheers!

**Comment by politas** [comment]
Ok, KSP-CKAN/CKAN-meta#1055 submitted.
